const banderasDelMundo = [
'Afganistán',
'Albania',
'Alemania',
'Andorra',
'Angola',
'Antigua y Barbuda',
'Arabia Saudita',
'Argelia',
'Argentina',
'Armenia',
'Australia',
'Austria',
'Azerbaiyán',
'Bahamas',
'Bangladés',
'Barbados',
'Baréin',
'Belice',
'Benín',
'Bielorrusia',
'Bolivia',
'Bosnia y Herzegovina',
'Botsuana',
'Brasil',
'Brunei',
'Bulgaria',
'Burkina Faso',
'Burundi',
'Bután',
'Bélgica',
'Cabo Verde',
'Camboya',
'Catar',
'Chad',
'Chile',
'China',
'Chipre',
'Colombia',
'Comoras',
'Corea del Norte',
'Corea del Sur',
'Costa de Marfil',
'Costa Rica',
'Croacia',
'Cuba',
'Dinamarca',
'Dominica',
'Ecuador',
'Egipto',
'El Salvador',
'Emiratos Árabes Unidos',
'Eritrea',
'Eslovaquia',
'España',
'Estados Unidos',
'Estonia',
'Esuatini',
'Etiopía',
'Filipinas',
'Finlandia',
'Fiyi',
'Francia',
'Gabón',
'Gambia',
'Georgia',
'Ghana',
'Granada',
'Grecia',
'Guatemala',
'Guayana Francesa',
'Guinea Ecuatorial',
'Guinea-Bissau',
'Guinea',
'Guyana',
'Haití',
'Honduras',
'Hungría',
'India',
'Indonesia',
'Iraq',
'Irlanda',
'Irán',
'Islandia',
'Islas Marshall',
'Islas Salomón',
'Israel',
'Italia',
'Jamaica',
'Japón',
'Jordania',
'Kazajistán',
'Kenia',
'Kirguistán',
'Kuwait',
'Laos',
'Lesoto',
'Liberia',
'Libia',
'Liechtenstein',
'Lituania',
'Luxemburgo',
'Líbano',
'Madagascar',
'Malasia',
'Malaui',
'Maldivas',
'Malta',
'Malí',
'Marruecos',
'Mauricio',
'Mauritania',
'Micronesia',
'Moldavia',
'Mongolia',
'Mozambique',
'Myanmar (Birmania)',
'México',
'Mónaco',
'Namibia',
'Nauru',
'Nepal',
'Nicaragua',
'Nigeria',
'Noruega',
'Nueva Zelanda',
'Níger',
'Omán',
'Pakistán',
'Palau',
'Palestina',
'Panamá',
'Papúa Nueva Guinea',
'Paraguay',
'Países Bajos',
'Perú',
'Polonia',
'Portugal',
'Puerto Rico',
'República Centroafricana',
'República Checa',
'República del Congo',
'República Democrática del Congo',
'República Dominicana',
'Reunión',
'Ruanda',
'Rumania',
'Rusia',
'Samoa',
'San Cristóbal y Nieves',
'San Marino',
'San Vicente y las Granadinas',
'Santa Lucía',
'Santo Tomé y Príncipe',
'Senegal',
'Serbia',
'Seychelles',
'Sierra Leona',
'Singapur',
'Somalia',
'Sri Lanka',
'Sudáfrica',
'Sudán del Sur',
'Sudán',
'Suecia',
'Suiza',
'Surinam',
'Siria',
'Tailandia',
'Taiwán',
'Tanzania',
'Tayikistán',
'Timor Oriental',
'Togo',
'Tonga',
'Trinidad y Tobago',
'Turkmenistán',
'Turquía',
'Tuvalu',
'Túnez',
'Ucrania',
'Uganda',
'Uruguay',
'Uzbekistán',
'Vanuatu',
'Vaticano',
'Venezuela',
'Vietnam',
'Yemen',
'Yibuti',
'Zambia',
'Zimbabue'
]

export class RANDOM {
    constructor() {}
    numeros() {
        return Math.floor(Math.random() * 10 )
    }
    letras(cantidadLetra) {
        const letras = ['q','w','e','r','t','y','u','i','o','p','a','s','d','f','g','h','j','k','l','z','x','c','v','b','n','m']
        const numerosAleatorios = []
        let listaRandom = ''
        for(let i = 0;i < cantidadLetra;i++) {
            const numero = Math.floor(Math.random() * letras.length)
            const letra = letras[numero]
            listaRandom += letra
        }
        return listaRandom
    }
    shuffleArray(array) {
        for (var i = array.length - 1; i > 0; i--) {
            var j = Math.floor(Math.random() * (i + 1));
            var temp = array[i];
            array[i] = array[j];
            array[j] = temp; // Intercambia elementos
        }
        return array;
    }
    banderaRandom() {
        const random = Math.floor(Math.random() * banderasDelMundo.length)
        const banderaRandom = banderasDelMundo[random]
        return banderaRandom
    }
}

